// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kgednxqhtoejurluogzx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnZWRueHFodG9lanVybHVvZ3p4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NzU1ODksImV4cCI6MjA2NDU1MTU4OX0.g4LaaEWOGng8TkFXX0KPTG5K3m516pnQbVV6siv3N1A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);